# -*- coding: utf-8 -*-
"""Sales_forecast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kmb4zguNvYZ4LqGQZAUhYgS_ZZNz-sMg
"""

!pip install prophet

import pandas as pd
from prophet import Prophet

"""Loading data into our notebook"""

dataframe = pd.read_csv('transactions.csv')

dataframe.head()

dataframe.dtypes

"""Data preprocessing"""

dataframe ['date'] = pd.to_datetime(dataframe ['date'])



dataframe.dtypes

dataframe.drop('store_nbr', axis=1, inplace=True)

dataframe.head()

dataframe.columns = ['ds', 'y']

dataframe.head()

"""Training the time series model"""

p = Prophet(interval_width=0.92, daily_seasonality=True)

model = p.fit(dataframe)

"""Making predictions and evaluating performance"""

future = p.make_future_dataframe(periods=200, freq='D')

future.tail()

forecast_prediction = p.predict(future)

forecast_prediction.tail()

"""Visualization"""

plot1 = p.plot(forecast_prediction)

plot2 = p.plot_components(forecast_prediction)